# Generated by Django 3.0 on 2020-04-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eunoiaapp', '0002_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('STARTUP', 'Startup'), ('ESTABLISHED', 'Established Company'), ('ENTERPRISE', 'Enterprise')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FOUNDER', 'Founder'), ('CEO', 'CEO'), ('PO', 'Product Owner'), ('SCRUM_MASTER', 'Scrum Master'), ('DEVELOPER', 'Developer'), ('GUEST', 'Guest')], max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='belongs_to_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='eunoiaapp.Company'),
            preserve_default=False,
        ),
    ]
